[package]
name = "widgets"
version.workspace = true
edition.workspace = true
license.workspace = true

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace]
members = ["table"]

[workspace.dependencies]
table = { version = "0.1.0", path = "table" }
iced = { version = "0.13.1", features = [
    "advanced",
    "highlighter",
    "tokio",
    "canvas",
] }

[dependencies]
iced.workspace = true
table.workspace = true

syntect = { version = "5.2", features = [] }
tokio = { version = "1.39.0", features = ["fs"] }

[dev-dependencies]
modav_core = { git = "ssh://github.com/EmmanuelDodoo/modav_core.git" }


[[example]]
name = "table"
path = "examples/table/main.rs"
