[package]
name = "widgets"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = [
    "advanced",
    "highlighter",
    "tokio",
    "canvas",
] }

syntect = { version = "5.2", features = [] }
iced_graphics = "0.13.0"
modav_core = { git = "ssh://github.com/EmmanuelDodoo/modav_core.git" }
tokio = { version = "1.39.0", features = ["fs"] }
